version: "3"

services:
    app:
        build: .
        restart: unless-stopped
        env_file: .env
        volumes:
            - ./:/var/www
        depends_on:
            - db
    nginx:
        image: nginx:1.17-alpine
        restart: unless-stopped
        ports:
            - 80:80
        volumes:
            - ./:/var/www
            - ./tools/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
    db:
        image: mysql:5.7
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            SERVICE_NAME: mysql
            SERVICE_TAGS: dev
