version: "3"

services:
    app:
        image: supavet/eatfoodwithyou
        restart: unless-stopped
        env_file: .env
        depends_on:
            - db
    nginx:
        image: supavet/nginx-eatfoodwithyou
        restart: unless-stopped
        ports:
            - 80:80
        depends_on:
            - app
    db:
        image: mysql:5.7
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            SERVICE_NAME: mysql
            SERVICE_TAGS: dev
